# extension/sql-manifest.dockerfile — GENERATED by gen-copy-manifest.sh.
# DO NOT EDIT BY HAND. Source of truth: extension_sql_file! calls in src/lib.rs.
#
# This is a readable standalone artifact (for humans/diffing) — Docker can't
# COPY the contents of another file's instructions in, so the SAME block is
# also written into extension/Dockerfile between the GENERATED markers; that
# copy is what the build actually reads.
COPY v00-foundations.sql ./
COPY v01-work-substrate.sql ./
COPY v02-governance.sql ./
COPY v03-fanout-brainstorm.sql ./
COPY v04-context-engine.sql ./
COPY v05-subagents.sql ./
COPY v06-agents-runtime.sql ./
COPY v07-agent-surface.sql ./
COPY v08-aliases-docbuilder.sql ./
COPY v09-routing-and-hinge.sql ./
COPY v10-chat.sql ./
COPY v11-loreworks.sql ./
COPY v12-rigor.sql ./
COPY v13-a2a.sql ./
COPY v14-search-and-disclosure.sql ./
COPY v15-world-graph.sql ./
COPY v16-code-graph.sql ./
COPY v17-gates-worldchat.sql ./
COPY v18-lab.sql ./
COPY v19-platform.sql ./
COPY v20-wiki.sql ./
COPY v21-crawler.sql ./
COPY v22-route-intake.sql ./
COPY v23-schedule-chat.sql ./
COPY v24-lab-dispatch.sql ./
COPY v25-war-game.sql ./
COPY v26-knowledge.sql ./
COPY v27-lifeless-core.sql ./
COPY v28-files-interface.sql ./
COPY v30-workspaces.sql ./
