// stewards-cli update — the one verb for "bring this box up to the repo's
// current code and DB shape."
//
// Runs the blessed sequence end to end, UNPIPED at every step (each step's
// real exit code is checked directly — no `| tail` masking a builder
// COMPILE error the way it did for 102-war-game.sql, 2026-07-06):
//
//	(a) git pull --ff-only              (repo root; refuses on non-ff)
//	(b) extension/gen-copy-manifest.sh --check
//	                                     (auto-regenerates + WARNs if the
//	                                      Dockerfile's COPY block drifted
//	                                      from lib.rs; hard-fails only if
//	                                      regeneration itself can't succeed)
//	(c) docker compose build            (skippable: --skip-build)
//	(d) docker compose up -d
//	(e) wait for the pg container to report healthy (120s cap)
//	(f) scripts/migrate.sh apply        (through a generated psql shim
//	                                      when the host has no native
//	                                      psql — see psqlShimScript below)
//	(g) tests/virgin-smoke.sql against a THROWAWAY scratch container
//	    booted from the image `docker compose build` just produced —
//	    never against the live `pg` service. (skippable: --skip-smoke)
//	(h) print step -> exit summary table
//
// Any step exiting non-zero stops the run right there (no partial-credit
// continuation) and prints what to do about it. --dry-run prints the plan
// without touching anything.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/tabwriter"
	"time"
)

const (
	updatePGContainer = "stewards-oss-pg"
	updateImageTag    = "stewards-oss-pg:pg18" // matches docker-compose.yaml's `image:` for the pg service
)

// psqlShimScript is written to a temp dir and prepended to PATH when the
// host has no native `psql` binary (`exec.LookPath("psql")` fails — true on
// a bare Windows dev box that only has Docker Desktop). It makes
// `bash scripts/migrate.sh apply` work unmodified by routing every psql
// invocation through `docker exec` into the running pg container.
//
// The one wrinkle a naive `exec docker exec -i "$@"` gets wrong: migrate.sh's
// apply_one() calls `psql "$DSN" ... -f "$f"` where $f is a HOST filesystem
// path (e.g. /c/.../extension/00-config.sql). That path does not exist
// INSIDE the container (extension/ isn't volume-mounted into pg), so a
// blind passthrough would fail every single file with "No such file". This
// shim special-cases -f: docker cp the file in first, rewrite the arg to
// the in-container path, then clean up. scripts/db.sh solved the identical
// problem for its own narrower -c/-f interface; this mirrors its two fixes:
//   - the docker-cp destination arg is left as-is (host-style paths in the
//     SOURCE position are meant to be MSYS-translated — that's correct)
//   - the exec's -f argument is given a LEADING DOUBLE SLASH ("//tmp/...")
//     because MSYS's automatic path-conversion mangles a bare "/tmp/x" into
//     a Windows path before docker ever sees it (db.sh's comment #2); the
//     double slash is the documented way to defeat that conversion for an
//     argument that must stay a literal in-container path.
//   - cleanup also uses the double-slash form: a bare single-slash cleanup
//     arg gets the identical MSYS mangling (verified against a live
//     throwaway container while building this shim — a single-slash rm
//     silently no-ops on the WRONG, Windows-translated path, leaving the
//     real in-container temp file behind), so it needs the same fix, not
//     just a shrug because `-f` swallows the error either way.
const psqlShimScript = `#!/usr/bin/env bash
# Generated by stewards-cli update (cmd/stewards-cli/update.go). Do not edit;
# it is regenerated (and deleted after use) every run.
set -euo pipefail
CONTAINER="${STEWARDS_SHIM_CONTAINER:-stewards-oss-pg}"
PASS="${STEWARDS_SHIM_PGPASSWORD:-stewards}"

args=()
cleanup_path=""
i=0
argv=("$@")
while [ $i -lt ${#argv[@]} ]; do
  a="${argv[$i]}"
  if [ "$a" = "-f" ]; then
    i=$((i + 1))
    hostfile="${argv[$i]}"
    base="$(basename "$hostfile")"
    tmpname="psql-shim-$$-$base"
    docker cp "$hostfile" "$CONTAINER:/tmp/$tmpname" >/dev/null
    # Leading double slash defeats MSYS mangling a plain /tmp/... arg into
    # a Windows host path before docker exec ever sees it (see db.sh).
    args+=("-f" "//tmp/$tmpname")
    cleanup_path="//tmp/$tmpname"
  else
    args+=("$a")
  fi
  i=$((i + 1))
done

rc=0
docker exec -i -e PGPASSWORD="$PASS" "$CONTAINER" psql "${args[@]}" || rc=$?
if [ -n "$cleanup_path" ]; then
  docker exec "$CONTAINER" rm -f "$cleanup_path" 2>/dev/null || true
fi
exit $rc
`

type updateStep struct {
	name   string
	status string // OK | WARN | FAIL | SKIP
	detail string
}

func runUpdate(_ context.Context, args []string) {
	fs := flag.NewFlagSet("update", flag.ExitOnError)
	skipBuild := fs.Bool("skip-build", false, "skip `docker compose build` (assume the image is already current)")
	skipSmoke := fs.Bool("skip-smoke", false, "skip the throwaway virgin-smoke verification against the fresh image")
	dryRun := fs.Bool("dry-run", false, "print the plan; make no changes")
	if err := fs.Parse(args); err != nil {
		os.Exit(1)
	}

	repoRoot, err := gitRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "update: %v\n", err)
		os.Exit(1)
	}

	plan := []string{
		"(a) git pull --ff-only",
		"(b) extension/gen-copy-manifest.sh --check (auto-regenerate + WARN if drifted)",
	}
	if *skipBuild {
		plan = append(plan, "(c) docker compose build  [SKIPPED: --skip-build]")
	} else {
		plan = append(plan, "(c) docker compose build")
	}
	plan = append(plan,
		"(d) docker compose up -d",
		fmt.Sprintf("(e) wait for %s to report healthy (120s cap)", updatePGContainer),
		"(f) scripts/migrate.sh apply (via generated psql shim if host lacks psql)",
	)
	if *skipSmoke {
		plan = append(plan, "(g) tests/virgin-smoke.sql vs. a throwaway scratch container from the fresh image  [SKIPPED: --skip-smoke]")
	} else {
		plan = append(plan, "(g) tests/virgin-smoke.sql vs. a throwaway scratch container from the fresh image (never the live pg)")
	}
	plan = append(plan, "(h) print step -> exit summary")

	if *dryRun {
		fmt.Println("stewards-cli update --dry-run — plan (no changes made):")
		for _, p := range plan {
			fmt.Printf("  %s\n", p)
		}
		fmt.Printf("\nrepo root: %s\n", repoRoot)
		if _, lookErr := exec.LookPath("psql"); lookErr != nil {
			fmt.Println("psql: NOT found on PATH -> step (f) would use the generated docker-exec shim")
		} else {
			fmt.Println("psql: found on PATH -> step (f) would run scripts/migrate.sh directly")
		}
		return
	}

	var steps []updateStep
	fail := func(name, detail string) {
		steps = append(steps, updateStep{name, "FAIL", detail})
		printUpdateSummary(steps)
		os.Exit(1)
	}

	// ---- (a) git pull --ff-only ----
	fmt.Println("== (a) git pull --ff-only ==")
	if rc, _ := runStreamed(repoRoot, nil, "git", "pull", "--ff-only"); rc != 0 {
		fail("git pull --ff-only", fmt.Sprintf("exit %d — not a fast-forward, or pull failed; resolve manually (fetch + rebase/merge) and re-run", rc))
	}
	steps = append(steps, updateStep{"git pull --ff-only", "OK", ""})

	// ---- (b) gen-copy-manifest.sh --check ----
	fmt.Println("\n== (b) extension/gen-copy-manifest.sh --check ==")
	if rc, _ := runStreamed(repoRoot, nil, "bash", "extension/gen-copy-manifest.sh", "--check"); rc == 0 {
		steps = append(steps, updateStep{"gen-copy-manifest --check", "OK", "Dockerfile COPY block matches lib.rs"})
	} else {
		fmt.Println("update: Dockerfile COPY block is stale — regenerating...")
		if rc2, _ := runStreamed(repoRoot, nil, "bash", "extension/gen-copy-manifest.sh"); rc2 != 0 {
			fail("gen-copy-manifest --check", "was stale AND regeneration failed — likely a chain file referenced in lib.rs is missing on disk; fix that first (see output above)")
		}
		steps = append(steps, updateStep{"gen-copy-manifest --check", "WARN", "was stale; regenerated extension/Dockerfile + sql-manifest.dockerfile — review and commit that diff"})
	}

	// ---- (c) docker compose build ----
	if *skipBuild {
		steps = append(steps, updateStep{"docker compose build", "SKIP", "--skip-build"})
	} else {
		fmt.Println("\n== (c) docker compose build ==")
		if rc, _ := runStreamed(repoRoot, nil, "docker", "compose", "build"); rc != 0 {
			fail("docker compose build", fmt.Sprintf("exit %d — see build output above", rc))
		}
		steps = append(steps, updateStep{"docker compose build", "OK", ""})
	}

	// ---- (d) docker compose up -d ----
	fmt.Println("\n== (d) docker compose up -d ==")
	if rc, _ := runStreamed(repoRoot, nil, "docker", "compose", "up", "-d"); rc != 0 {
		fail("docker compose up -d", fmt.Sprintf("exit %d — see output above", rc))
	}
	steps = append(steps, updateStep{"docker compose up -d", "OK", ""})

	// ---- (e) wait for pg healthy ----
	fmt.Printf("\n== (e) waiting for %s to report healthy (120s cap) ==\n", updatePGContainer)
	if err := waitHealthy(updatePGContainer, 120*time.Second); err != nil {
		if out, lerr := exec.Command("docker", "logs", "--tail", "50", updatePGContainer).CombinedOutput(); lerr == nil {
			fmt.Fprintln(os.Stderr, string(out))
		}
		fail("wait for pg healthy", fmt.Sprintf("%v — see `docker compose logs pg` (last 50 lines printed above)", err))
	}
	steps = append(steps, updateStep{"wait for pg healthy", "OK", ""})

	// ---- (f) scripts/migrate.sh apply ----
	fmt.Println("\n== (f) scripts/migrate.sh apply ==")
	shimDir, shimCleanup, err := maybePsqlShim()
	if err != nil {
		fail("scripts/migrate.sh apply", fmt.Sprintf("could not prepare psql shim: %v", err))
	}
	defer shimCleanup()

	env := os.Environ()
	usingShim := shimDir != ""
	if usingShim {
		env = prependPath(env, shimDir)
		env = append(env, "STEWARDS_SHIM_CONTAINER="+updatePGContainer)
		env = append(env, "STEWARDS_SHIM_PGPASSWORD="+envOr("POSTGRES_PASSWORD", "stewards"))
		fmt.Println("psql not found on host — routing scripts/migrate.sh through a docker-exec shim into", updatePGContainer)
		if os.Getenv("STEWARDS_DSN") == "" {
			// The shim execs INSIDE the container, where Postgres listens on
			// its own internal 5432 — this is migrate.sh's own built-in
			// default, set explicitly here so the run is reproducible
			// regardless of the caller's shell state.
			env = append(env, "STEWARDS_DSN=postgres://stewards:stewards@localhost:5432/stewards?sslmode=disable")
		}
	} else if os.Getenv("STEWARDS_DSN") == "" {
		// Real local psql — talk to the host-mapped port (docker-compose.yaml
		// publishes the container's 5432 to PG_PORT, default 55434).
		port := envOr("PG_PORT", "55434")
		env = append(env, fmt.Sprintf("STEWARDS_DSN=postgres://stewards:stewards@localhost:%s/stewards?sslmode=disable", port))
	}

	if rc, _ := runStreamedEnv(repoRoot, env, "bash", "scripts/migrate.sh", "apply"); rc != 0 {
		fail("scripts/migrate.sh apply", fmt.Sprintf("exit %d — see output above", rc))
	}
	detail := ""
	if usingShim {
		detail = "via psql shim (host has no native psql)"
	}
	steps = append(steps, updateStep{"scripts/migrate.sh apply", "OK", detail})

	// ---- (g) virgin-smoke against a throwaway scratch container ----
	if *skipSmoke {
		steps = append(steps, updateStep{"virgin-smoke (throwaway)", "SKIP", "--skip-smoke"})
	} else {
		fmt.Println("\n== (g) tests/virgin-smoke.sql against a throwaway scratch container ==")
		if err := runVirginSmoke(repoRoot); err != nil {
			fail("virgin-smoke (throwaway)", err.Error())
		}
		steps = append(steps, updateStep{"virgin-smoke (throwaway)", "OK", "fresh image proven clean-room installable"})
	}

	printUpdateSummary(steps)
}

// ---------- helpers ----------

func gitRepoRoot() (string, error) {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", fmt.Errorf("not inside a git repo (or git not on PATH): %w", err)
	}
	root := strings.TrimSpace(string(out))
	// git on Windows (MSYS) prints a posix-style path; filepath.FromSlash is a
	// no-op on Linux and normalizes separators for any downstream os/exec use.
	return filepath.FromSlash(root), nil
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// runStreamed runs a command with the given working directory (nil env =
// inherit the current process's environment), connecting stdout/stderr
// directly to this process's so output streams live. Returns the REAL exit
// code, checked directly by every caller above — never piped through
// anything that could mask it.
func runStreamed(dir string, env []string, name string, args ...string) (int, error) {
	return runStreamedEnv(dir, env, name, args...)
}

func runStreamedEnv(dir string, env []string, name string, args ...string) (int, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	if env != nil {
		cmd.Env = env
	}
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	err := cmd.Run()
	if err == nil {
		return 0, nil
	}
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		return exitErr.ExitCode(), err
	}
	return -1, err // failed to even start (binary missing, etc.)
}

// waitHealthy polls `docker inspect` for a compose-managed container's
// health status (the pg service declares a HEALTHCHECK in
// docker-compose.yaml) until it reports "healthy" or the cap elapses.
func waitHealthy(container string, cap time.Duration) error {
	deadline := time.Now().Add(cap)
	var lastStatus string
	for time.Now().Before(deadline) {
		out, err := exec.Command("docker", "inspect", "--format={{.State.Health.Status}}", container).CombinedOutput()
		lastStatus = strings.TrimSpace(string(out))
		if err == nil && lastStatus == "healthy" {
			return nil
		}
		time.Sleep(2 * time.Second)
	}
	if lastStatus == "" {
		lastStatus = "(no status — container may not exist or have no healthcheck)"
	}
	return fmt.Errorf("did not reach 'healthy' within %s (last status: %s)", cap, lastStatus)
}

// maybePsqlShim returns a directory containing a `psql` shim script (and a
// cleanup func) when the host has no native psql on PATH. Returns ("", noop,
// nil) when a real psql is already available — callers should prefer that
// and leave scripts/migrate.sh to run against it directly.
func maybePsqlShim() (dir string, cleanup func(), err error) {
	cleanup = func() {}
	if _, lookErr := exec.LookPath("psql"); lookErr == nil {
		return "", cleanup, nil
	}
	d, err := os.MkdirTemp("", "stewards-psql-shim-*")
	if err != nil {
		return "", cleanup, fmt.Errorf("create shim dir: %w", err)
	}
	scriptPath := filepath.Join(d, "psql")
	if err := os.WriteFile(scriptPath, []byte(psqlShimScript), 0o755); err != nil {
		os.RemoveAll(d)
		return "", cleanup, fmt.Errorf("write shim script: %w", err)
	}
	return d, func() { os.RemoveAll(d) }, nil
}

// prependPath puts dir first in the PATH entry of env (or adds one).
func prependPath(env []string, dir string) []string {
	out := make([]string, 0, len(env)+1)
	found := false
	for _, e := range env {
		if len(e) >= 5 && strings.EqualFold(e[:5], "PATH=") {
			out = append(out, "PATH="+dir+string(os.PathListSeparator)+e[5:])
			found = true
			continue
		}
		out = append(out, e)
	}
	if !found {
		out = append(out, "PATH="+dir)
	}
	return out
}

// runVirginSmoke builds nothing (the image was already built in step (c));
// it boots a throwaway, uniquely-named container from that image, waits for
// pg_isready, streams tests/virgin-smoke.sql into it via `docker exec -i`,
// and always tears the container down — success or failure, and NEVER
// touching the live `pg` service.
func runVirginSmoke(repoRoot string) error {
	name := fmt.Sprintf("stewards-oss-update-smoke-%d", time.Now().UnixNano())
	// Best-effort pre-clean in case a prior run's teardown was interrupted.
	_ = exec.Command("docker", "rm", "-f", name).Run()

	runArgs := []string{
		"run", "-d", "--name", name,
		"-e", "POSTGRES_USER=stewards",
		"-e", "POSTGRES_PASSWORD=smoketest",
		"-e", "POSTGRES_DB=stewards",
		updateImageTag,
		"-c", "shared_preload_libraries=pg_ai_stewards",
	}
	if rc, _ := runStreamedEnv(repoRoot, nil, "docker", runArgs...); rc != 0 {
		return fmt.Errorf("docker run (throwaway smoke container) failed with exit %d", rc)
	}
	defer func() { _ = exec.Command("docker", "rm", "-f", name).Run() }()

	ready := false
	deadline := time.Now().Add(60 * time.Second)
	for time.Now().Before(deadline) {
		if err := exec.Command("docker", "exec", name, "pg_isready", "-U", "stewards", "-d", "stewards").Run(); err == nil {
			ready = true
			break
		}
		time.Sleep(2 * time.Second)
	}
	if !ready {
		out, _ := exec.Command("docker", "logs", "--tail", "50", name).CombinedOutput()
		fmt.Fprintln(os.Stderr, string(out))
		return fmt.Errorf("throwaway smoke container did not become ready within 60s")
	}

	smokeFile := filepath.Join(repoRoot, "tests", "virgin-smoke.sql")
	f, err := os.Open(smokeFile)
	if err != nil {
		return fmt.Errorf("open %s: %w", smokeFile, err)
	}
	defer f.Close()

	cmd := exec.Command("docker", "exec", "-i", name, "psql", "-U", "stewards", "-d", "stewards", "-v", "ON_ERROR_STOP=1")
	cmd.Stdin = f
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("virgin-smoke.sql FAILED against the fresh image: %w", err)
	}
	return nil
}

func printUpdateSummary(steps []updateStep) {
	fmt.Println("\n== stewards-cli update: summary ==")
	tw := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Fprintln(tw, "STEP\tSTATUS\tDETAIL")
	for _, s := range steps {
		fmt.Fprintf(tw, "%s\t%s\t%s\n", s.name, s.status, s.detail)
	}
	tw.Flush()
}
